# SPDX-FileCopyrightText: 2024 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "opensipi"
SPDX-PackageSupplier = "Yansheng Wang <yanshengw@rivosinc.com>"
SPDX-PackageDownloadLocation = "https://github.com/rivosinc/opensipi"

[[annotations]]
path = "examples/Olympus/Sim_Input/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Rivos Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/Figures/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Rivos Inc."
SPDX-License-Identifier = "Apache-2.0"
