{
  design_type: PCB,
  dsn_name: 2-SLOT_48LANE_RISER.brd,
  logoimg_dir: /home/yanshengw/opensipi_config/Company_logo.png,
  proj_name: Olympus,
  report_dir: /work/yanshengw/OpenSIPI/Olympus/Xtract/Run_20240819_120532/Report/,
  report_full_path: /work/yanshengw/OpenSIPI/Olympus/Xtract/Run_20240819_120532/Report/report_20240819_120532.pdf,
  report_type: IO,
  result_dir: /work/yanshengw/OpenSIPI/Olympus/Xtract/Run_20240819_120532/Result/,
  sim_date: "20240819_120532",
  usr_id: user_id,
  xtract_tool: Sigrity,
  xtract_type: HSIO,
}
